[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[lib]
name = "chess"
path = "src/lib.rs"

[dependencies]
regex = "1.12.2"
rand = "0.9.2"

[profile.dev]
# Compile dev builds with zero optimizations for faster compile times and easier debugging
opt-level = 0
debug = true
incremental = true
lto = "off"
