[package]
name = "rokade-ai-chess"
version = "0.3.0"
edition = "2024"
build = "build.rs"

[lib]
name = "chess"
path = "src/lib.rs"

[dependencies]
regex = "1.12.2"
rand = "0.9.3"
bitflags = "2.6"

# Optional parallel Search (enable with `--features parallel`)
rayon = { version = "1", optional = true }
chrono = "0.4.42"

[features]
default = ["parallel"]
#default = ["parallel", "debug-search"]
parallel = ["rayon"]
# Enable verbose search tracing output (iterative deepening, alphabeta, qsearch)
# Usage: cargo run --features debug-search
debug-search = []

[build-dependencies]

[profile.dev]
# Compile dev builds with zero optimizations for faster compile times and easier debugging
opt-level = 0
debug = true
incremental = true
lto = "off"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
[[bin]]
name = "rokade-ai-chess"
path = "src/chess_main.rs"

[profile.bench]
debug=true

[profile.engine]
inherits = "release"

[[bin]]
name = "rokade-ai-chess-engine"
path = "src/engine_main.rs"

[dev-dependencies]
#serial_test = "*"
